✨ 添加分片函数
FloatTech/floatbox pull request #2
Opened 2023-02-15 17:29 UTC by guohuiyuan

2023-02-16 09:16 UTC, fumiama requested changes

2023-02-16 09:16 UTC, fumiama commented on list/list.go
> +	for i := 0; i < plen; i++ {
for i := 0; i < plen-1; i++，然后最后一个单独填充。要尽量减少循环内的分支判断。

2023-02-16 09:16 UTC, fumiama commented on list/list.go
> +func Partition[T any](list []T, size int) (plist [][]T) {
换个签名吧，如`SplitN(arr []T, n int)`

2023-02-16 09:16 UTC, fumiama commented on list/list.go
> +package list
我建议放在 math 包，不值得为一个函数弄个新包。

2023-02-16 11:10 UTC, guohuiyuan commented
名字，java这边都叫partition




开心
***@***.***







                       
Original Email
                       
                     

Sender:"源文雨"< ***@***.*** &gt;;

Sent Time:2023/2/16 17:16

To:"FloatTech/floatbox"< ***@***.*** &gt;;

Cc recipient:"himawari"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [FloatTech/floatbox] ✨ 添加分片函数 (PR #2)




 
@fumiama requested changes on this pull request.
 
 
In list/list.go:
 &gt; @@ -0,0 +1,18 @@ +// Package list 分片函数 +package list + +import &quot;math&quot; + +// Partition 分片函数 +func Partition[T any](list []T, size int) (plist [][]T) { +	plen := int(math.Ceil(float64(len(list)) / float64(size))) +	plist = make([][]T, plen) +	for i := 0; i < plen; i++ {  
for i := 0; i < plen-1; i++，然后最后一个单独填充。要尽量减少循环内的分支判断。
 
 
In list/list.go:
 &gt; @@ -0,0 +1,18 @@ +// Package list 分片函数 +package list + +import &quot;math&quot; + +// Partition 分片函数 +func Partition[T any](list []T, size int) (plist [][]T) {  
换个签名吧，如SplitN(arr []T, n int)
 
 
In list/list.go:
 &gt; @@ -0,0 +1,18 @@ +// Package list 分片函数 +package list  
我建议放在 math 包，不值得为一个函数弄个新包。
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-02-16 11:53 UTC, fumiama requested changes

2023-02-16 11:53 UTC, fumiama commented on math/math.go
> +func Partition[T any](list []T, size int) (plist [][]T) {
对不起，这里是Go

2023-02-16 11:53 UTC, fumiama commented on math/math.go
> +	plist = make([][]T, plen)
要先检查size，做不同操作。<=0直接返回nil，1返回本身，2及以上才开始计算。

2023-02-20 12:16 UTC, guohuiyuan commented on math/math.go
> +	plist = make([][]T, plen)
1不是返回本身, 他是一个二维切片，后面的处理可以通用

2023-02-21 08:32 UTC, fumiama requested changes

2023-02-21 08:32 UTC, fumiama commented on math/math.go
> +	plist = make([][]T, plen)
呃呃，有没有一种可能就是说我指的“本身”是
```go
return [][]T{list}
```
至于能否通用，那当然是可以的，但是这样就有点晦涩了，我不建议这么干。

2024-03-04 06:41 UTC, fumiama approved these changes

2024-03-04 06:41 UTC, merged